Resources:
        sslSecurityGroupIngress:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
        GroupId: {"Fn::GetAtt" : ["AWSEBSecurityGroup", "sg-0116a29d9448d8f50"]}
        IpProtocol: tcp
        ToPort: 1000
        FromPort: 1000
        SourceSecurityGroupId: {"Fn::GetAtt" : ["AWSEBLoadBalancerSecurityGroup", "sg-00ed524009eba9358"]}]
        